export const PUSH_T0_SELECTED_OPTIONS = "PUSH_T0_SELECTED_OPTIONS";
export const POP_FROM_SELECTED_OPTIONS = "POP_FROM_SELECTED_OPTIONS";
export const RESET = "RESET";
export const SHUFFLE = "SHUFFLE";
